class TestFailure(Exception):
    """Custom exception raised when a test fails."""

    def __init__(self, message: str, original_error: Exception = None):
        self.message = message
        self.original_error = original_error
        super().__init__(self.message)
